<?xml version="1.0" encoding="utf-8"?><Database Name="FoodBankDB" Class="L2S_FoodBankDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=BOBBYS-PC\SQLEXPRESS;Initial Catalog=FoodBankDB;Integrated Security=True;Pooling=False" SettingsObjectName="FoodBankInventoryManager.Properties.Settings" SettingsPropertyName="FoodBankDBConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Bin" Member="Bins">
    <Type Name="Bin">
      <Column Name="BinId" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Bin_InventoryEntry" Member="InventoryEntries" ThisKey="BinId" OtherKey="BinId" Type="InventoryEntry" />
    </Type>
  </Table>
  <Table Name="dbo.Shelf" Member="Shelfs">
    <Type Name="Shelf">
      <Column Name="ShelfId" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Shelf_InventoryEntry" Member="InventoryEntries" ThisKey="ShelfId" OtherKey="ShelfId" Type="InventoryEntry" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="Char(60) NOT NULL" CanBeNull="false" />
      <Column Name="AccessLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_InventoryEntry" Member="InventoryEntries" ThisKey="UserId" OtherKey="UserId" Type="InventoryEntry" />
    </Type>
  </Table>
  <Table Name="dbo.Food" Member="Foods">
    <Type Name="Food">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FoodName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AverageQty" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MinimumQty" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FoodId" Type="System.String" DbType="VarChar(31)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Food_InventoryEntry" Member="InventoryEntries" ThisKey="FoodName" OtherKey="FoodName" Type="InventoryEntry" />
    </Type>
  </Table>
  <Table Name="dbo.InventoryEntry" Member="InventoryEntries">
    <Type Name="InventoryEntry">
      <Column Name="EntryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FoodName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BinId" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ShelfId" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BinQty" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateEntered" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Bin_InventoryEntry" Member="Bin" ThisKey="BinId" OtherKey="BinId" Type="Bin" IsForeignKey="true" />
      <Association Name="Food_InventoryEntry" Member="Food" ThisKey="FoodName" OtherKey="FoodName" Type="Food" IsForeignKey="true" />
      <Association Name="Shelf_InventoryEntry" Member="Shelf" ThisKey="ShelfId" OtherKey="ShelfId" Type="Shelf" IsForeignKey="true" />
      <Association Name="User_InventoryEntry" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AuditEntry" Member="AuditEntries">
    <Type Name="AuditEntry">
      <Column Name="AuditEntryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FoodName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Binid" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ShelfId" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BinQty" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date_Action_Occured" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AccessLevel" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Action" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>